
FROM node:latest as build

ARG REACT_APP_AUTH0_FRONTEND_CLIENT_ID
ARG REACT_APP_AUTH0_FRONTEND_CLIENT_SECRET
ARG REACT_APP_AUTH0_DOMAIN
ARG REACT_APP_SERVER_ADDRESS
ARG REACT_APP_SERVER_AUDIENCE
ENV REACT_APP_AUTH0_FRONTEND_CLIENT_ID $REACT_APP_AUTH0_FRONTEND_CLIENT_ID
ENV REACT_APP_AUTH0_FRONTEND_CLIENT_SECRET $REACT_APP_AUTH0_FRONTEND_CLIENT_SECRET
ENV REACT_APP_AUTH0_DOMAIN $REACT_APP_AUTH0_DOMAIN
ENV REACT_APP_SERVER_ADDRESS $REACT_APP_SERVER_ADDRESS
ENV REACT_APP_SERVER_AUDIENCE $REACT_APP_SERVER_AUDIENCE

WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build


FROM node:18-alpine

ARG SERVER_PORT
ENV SERVER_PORT $SERVER_PORT

WORKDIR /app
COPY --from=build /app/build ./build
RUN npm install express nodemon
COPY package*.json ./
COPY server.js ./
EXPOSE 3000

ARG REACT_APP_AUTH0_FRONTEND_CLIENT_ID
ARG REACT_APP_AUTH0_FRONTEND_CLIENT_SECRET
ARG REACT_APP_AUTH0_DOMAIN
ARG REACT_APP_SERVER_ADDRESS
ARG REACT_APP_SERVER_AUDIENCE
ARG SERVER_PORT
ENV REACT_APP_AUTH0_FRONTEND_CLIENT_ID=$REACT_APP_AUTH0_FRONTEND_CLIENT_ID
ENV REACT_APP_AUTH0_FRONTEND_CLIENT_SECRET=$REACT_APP_AUTH0_FRONTEND_CLIENT_ID
ENV REACT_APP_AUTH0_DOMAIN=$REACT_APP_AUTH0_FRONTEND_CLIENT_ID
ENV REACT_APP_SERVER_ADDRESS=$REACT_APP_AUTH0_FRONTEND_CLIENT_ID
ENV REACT_APP_SERVER_AUDIENCE=$REACT_APP_AUTH0_FRONTEND_CLIENT_ID
ENV SERVER_PORT=$REACT_APP_AUTH0_FRONTEND_CLIENT_ID

CMD ["npm", "run", "dev"]